-- 0029_control_guidance.sql
-- Per-control teaching content so each control page is specific, not a blank
-- template: "guidance" = how to actually satisfy the control; "suggested_evidence"
-- = the artifacts an auditor typically expects (newline-separated, rendered as a
-- bullet list). Both live on the GLOBAL controls reference table (no tenant data,
-- already member-readable via the existing controls SELECT policy — no RLS change).

alter table public.controls
  add column if not exists guidance text,
  add column if not exists suggested_evidence text;

update public.controls c
set guidance = v.guidance,
    suggested_evidence = v.evidence
from (values
  -- ===== SOC 2 =====
  ('soc2','CC1.1','Publish a code of conduct and have every employee acknowledge it at hire and annually. Define how violations are reported and handled.',
    E'Signed code of conduct or employee handbook\nAcknowledgement records for all staff\nEthics / whistleblower reporting policy'),
  ('soc2','CC1.2','Hold and document regular leadership or board reviews of security, with minutes that show decisions and follow-ups.',
    E'Leadership or board meeting minutes referencing security\nOrg chart showing security oversight\nDefined security review cadence'),
  ('soc2','CC2.1','Define what security information is communicated, to whom, and how often, internally and to customers, and keep records of it.',
    E'Internal security announcements (Slack or email)\nCustomer-facing security page or Trust Center\nCommunication policy'),
  ('soc2','CC3.1','Run a documented risk assessment at least annually: identify threats to your data and systems, rate likelihood and impact, and record treatment decisions.',
    E'Risk assessment or risk register\nRisk methodology document\nEvidence of management review'),
  ('soc2','CC4.1','Continuously monitor that controls operate, through automated checks, log review, and periodic internal audits, and track findings to closure.',
    E'Internal audit or control-review records\nMonitoring dashboards\nRemediation tickets'),
  ('soc2','CC5.1','Map your policies to specific control activities and assign an owner to each, so every risk has a concrete control someone is accountable for.',
    E'Control matrix mapping risks to controls to owners\nPolicy documents\nOwner assignments'),
  ('soc2','CC6.1','Enforce least-privilege access to systems and data, require SSO and MFA, and review who has access on a set cadence.',
    E'IdP or SSO configuration showing MFA enforced\nAccess-control policy\nPeriodic access-review records'),
  ('soc2','CC6.2','Provision access through an approved request workflow on hire and role change, and tie every account to a named individual.',
    E'Onboarding or access-request tickets with approvals\nNew-hire provisioning checklist\nIdP user list'),
  ('soc2','CC6.3','Revoke access promptly on termination or role change (target same business day) and confirm removal across all systems.',
    E'Offboarding tickets with timestamps\nDeprovisioning checklist\nAccess review showing no orphaned accounts'),
  ('soc2','CC6.6','Protect the perimeter of your systems with firewalls and security groups, restrict ingress, encrypt public endpoints, and deny by default.',
    E'Firewall or security-group rule sets\nNetwork diagram\nTLS configuration for public endpoints'),
  ('soc2','CC7.1','Continuously scan infrastructure and dependencies for vulnerabilities and triage findings by severity against an SLA.',
    E'Vulnerability scan reports (SAST, DAST, dependency)\nScan schedule\nRemediation tickets with SLA'),
  ('soc2','CC7.2','Centralize logs and alert on suspicious activity, and make someone responsible for reviewing and acting on alerts.',
    E'Log aggregation or SIEM configuration\nAlerting rules\nSample alert with its disposition'),
  ('soc2','CC7.3','Maintain an incident response plan with roles, severity levels, and communication steps, and test it at least annually.',
    E'Incident response plan\nTabletop or test record\nPost-incident reviews'),
  ('soc2','CC8.1','Require peer review and approval for production changes, with an auditable trail across pull requests, CI checks, and deploy logs.',
    E'Pull-request history with reviews\nBranch-protection settings\nChange or deployment log'),
  ('soc2','CC9.1','Identify business-disruption and vendor risks and put mitigations in place, such as BCP/DR, vendor assessments, and insurance.',
    E'Business continuity and DR plan\nVendor risk assessments\nInsurance certificate'),

  -- ===== ISO 27001:2022 =====
  ('iso27001','A.5.1','Maintain a top-level information security policy approved by management, reviewed at least annually, and communicated to all staff.',
    E'Approved infosec policy with version and date\nManagement approval record\nStaff acknowledgements'),
  ('iso27001','A.5.7','Collect and act on threat intelligence relevant to your stack (vendor advisories, CVE feeds, sector alerts) and feed it into risk and patching.',
    E'Threat-intel feeds or subscriptions used\nRecord of advisories reviewed\nTickets actioned from intel'),
  ('iso27001','A.5.15','Define an access-control policy based on least privilege and need-to-know, covering joiners, movers, leavers, and periodic reviews.',
    E'Access-control policy\nRole and permission matrix\nAccess-review records'),
  ('iso27001','A.5.23','Set requirements for selecting, securing, and monitoring cloud services, including shared-responsibility and exit considerations.',
    E'Cloud security policy or standard\nCloud provider configuration (e.g. CIS benchmarks)\nVendor assessment for cloud providers'),
  ('iso27001','A.6.3','Deliver security awareness training to all personnel at onboarding and at least annually, and track completion.',
    E'Training completion report or roster\nTraining content or curriculum\nOnboarding checklist that includes security training'),
  ('iso27001','A.7.1','Define and protect physical perimeters for premises holding systems or data; for cloud-only, document reliance on provider data-centre controls.',
    E'Office or facility access policy\nVisitor log\nCloud provider physical-security attestation'),
  ('iso27001','A.8.1','Manage endpoints with disk encryption, screen lock, patching, and the ability to wipe lost devices, using MDM where possible.',
    E'MDM or endpoint-management configuration\nDisk-encryption report\nEndpoint security policy'),
  ('iso27001','A.8.5','Enforce strong authentication: SSO with MFA, a secure password policy, and protection against brute force.',
    E'IdP MFA enforcement\nPassword policy\nAuthentication configuration'),
  ('iso27001','A.8.8','Identify technical vulnerabilities through scanning, assess exposure, and remediate within risk-based timelines.',
    E'Vulnerability scan reports\nRemediation SLA or policy\nSample remediated finding'),
  ('iso27001','A.8.9','Define and enforce secure baseline configurations for systems and cloud, and detect drift from them.',
    E'Hardening baselines (CIS)\nInfrastructure-as-code templates\nConfiguration or drift monitoring output'),
  ('iso27001','A.8.13','Back up critical data on a defined schedule, encrypt backups, and test restoration periodically.',
    E'Backup configuration\nBackup success logs\nRestore-test record'),
  ('iso27001','A.8.15','Generate, protect, and retain logs of user activity, exceptions, and security events across key systems.',
    E'Logging configuration\nLog retention setting\nSample log export'),
  ('iso27001','A.8.16','Monitor systems and networks for anomalous behaviour and alert the responsible staff.',
    E'Monitoring or SIEM configuration\nAlert rules\nSample alert with response'),
  ('iso27001','A.8.24','Define a cryptography policy and enforce encryption in transit (TLS) and at rest, with proper key management.',
    E'Encryption policy\nTLS configuration\nAt-rest encryption settings (e.g. KMS)'),
  ('iso27001','A.8.28','Apply secure-coding standards, code review, and dependency or security scanning across your SDLC.',
    E'Secure coding guidelines\nPull-request review evidence\nSAST or dependency-scan results'),

  -- ===== HIPAA =====
  ('hipaa','164.308(a)(1)','Run a HIPAA risk analysis, implement a risk management plan, apply a sanction policy, and review system activity regularly.',
    E'Risk analysis and risk management plan\nSanction policy\nLog-review records'),
  ('hipaa','164.308(a)(2)','Formally designate a Security Official responsible for HIPAA policies and procedures.',
    E'Appointment letter or job description naming the Security Official\nOrg chart'),
  ('hipaa','164.308(a)(3)','Ensure only authorized workforce members access ePHI through authorization, clearance, and termination procedures.',
    E'Access authorization records\nBackground-check policy\nTermination or deprovisioning checklist'),
  ('hipaa','164.308(a)(4)','Grant ePHI access on a least-privilege, role-based basis and document authorization and modification.',
    E'Access-control policy\nRole definitions\nAccess request and approval records'),
  ('hipaa','164.308(a)(5)','Provide security awareness training (malware, login monitoring, password management) to all workforce members.',
    E'Training records\nTraining materials\nPeriodic security reminders'),
  ('hipaa','164.308(a)(6)','Maintain procedures to identify, respond to, and document security incidents, including breach assessment.',
    E'Incident response procedure\nIncident log\nBreach risk-assessment template'),
  ('hipaa','164.308(a)(7)','Establish data backup, disaster recovery, and emergency-mode operation plans, and test them.',
    E'Backup plan\nDisaster recovery plan\nTest results'),
  ('hipaa','164.308(a)(8)','Periodically evaluate your security posture against HIPAA requirements, technical and non-technical, and document findings.',
    E'Periodic HIPAA evaluation or audit report\nRemediation tracker'),
  ('hipaa','164.310(a)(1)','Limit physical access to facilities housing ePHI systems; for cloud, rely on and document the provider controls.',
    E'Facility access policy\nVisitor logs\nCloud provider physical-security attestation'),
  ('hipaa','164.310(b)','Define proper workstation use and physically safeguard workstations that access ePHI.',
    E'Workstation use policy\nScreen-lock or endpoint configuration\nDescription of physical safeguards'),
  ('hipaa','164.310(d)(1)','Control receipt, removal, reuse, and disposal of hardware and media containing ePHI, including secure wiping.',
    E'Media disposal or sanitization policy\nDisposal records\nEncryption of portable media'),
  ('hipaa','164.312(a)(1)','Implement unique user IDs, automatic logoff, and encryption for ePHI access.',
    E'Unique-ID or IdP configuration\nSession-timeout setting\nEncryption configuration'),
  ('hipaa','164.312(b)','Record and examine activity in systems that contain or use ePHI.',
    E'Audit-logging configuration\nLog retention setting\nSample access logs'),
  ('hipaa','164.312(c)(1)','Protect ePHI from improper alteration or destruction, with mechanisms to detect changes.',
    E'Integrity controls (checksums or versioning)\nChange logs\nBackup configuration'),
  ('hipaa','164.312(d)','Verify that persons or entities seeking ePHI access are who they claim to be by enforcing MFA.',
    E'MFA enforcement\nAuthentication policy\nIdP configuration'),
  ('hipaa','164.312(e)(1)','Encrypt ePHI in transit and guard against improper modification during transmission.',
    E'TLS configuration\nVPN or encryption settings\nData-in-transit policy'),

  -- ===== PCI DSS =====
  ('pci-dss','Req 1','Install and maintain network security controls (firewalls) between the cardholder data environment and untrusted networks.',
    E'Firewall or security-group rule sets\nNetwork diagram showing CDE segmentation\nRule-review records'),
  ('pci-dss','Req 2','Apply secure configuration standards to all system components; change vendor defaults and remove unnecessary services.',
    E'Hardening standards (CIS)\nConfiguration baselines\nEvidence that defaults were changed'),
  ('pci-dss','Req 3','Minimize stored cardholder data and render PAN unreadable (encryption, truncation, or tokenization); never store sensitive auth data after authorization.',
    E'Data-retention policy\nEncryption or tokenization configuration\nData-flow diagram'),
  ('pci-dss','Req 4','Encrypt cardholder data with strong cryptography during transmission over open or public networks.',
    E'TLS configuration\nCertificate inventory\nList of transmission channels'),
  ('pci-dss','Req 5','Protect all systems against malware and keep anti-malware mechanisms current and active.',
    E'Endpoint or anti-malware deployment report\nDefinition-update settings\nScan logs'),
  ('pci-dss','Req 6','Develop and maintain secure systems; patch promptly and follow secure SDLC practices.',
    E'Patch management records\nSecure-SDLC policy\nCode-review or SAST evidence'),
  ('pci-dss','Req 7','Restrict access to cardholder data by business need-to-know, with role-based access and default-deny.',
    E'Access-control policy\nRole and permission matrix\nAccess-review records'),
  ('pci-dss','Req 8','Assign unique IDs and enforce strong authentication (MFA) for all access to system components.',
    E'IdP or MFA configuration\nUnique-ID policy\nPassword parameters'),
  ('pci-dss','Req 9','Restrict physical access to cardholder data; for cloud, rely on and document the provider data-centre controls.',
    E'Physical access policy\nVisitor logs\nCloud provider attestation (AOC)'),
  ('pci-dss','Req 10','Log and monitor all access to system components and cardholder data; retain logs and review them daily.',
    E'Centralized logging configuration\nLog retention (at least 1 year)\nDaily-review records'),
  ('pci-dss','Req 11','Regularly test security with internal and external vulnerability scans and penetration tests, and remediate findings.',
    E'ASV or internal scan reports\nPenetration-test report\nRemediation tickets'),
  ('pci-dss','Req 12','Maintain an overarching information security policy and a security awareness program, and perform an annual risk assessment.',
    E'Information security policy\nAwareness-training records\nAnnual risk assessment'),

  -- ===== GDPR =====
  ('gdpr','Art. 5','Demonstrate the core principles across your processing: lawfulness, fairness, transparency, minimisation, accuracy, storage limitation, and integrity.',
    E'Data protection policy\nData inventory or RoPA\nRetention schedule'),
  ('gdpr','Art. 6','Identify and document a lawful basis for each processing activity.',
    E'Lawful-basis mapping per processing activity\nRoPA\nPrivacy notice'),
  ('gdpr','Art. 7','Where you rely on consent, make it freely given, specific, informed, and as easy to withdraw as to give.',
    E'Consent capture mechanism or screenshots\nConsent records or logs\nWithdrawal mechanism'),
  ('gdpr','Art. 13-14','Provide clear privacy notices at the point of data collection, whether collected directly or indirectly.',
    E'Published privacy notice\nCollection-point notices\nVersion history'),
  ('gdpr','Art. 15','Enable data subjects to obtain confirmation and a copy of their personal data, and respond within one month.',
    E'DSAR procedure\nDSAR request log\nSample fulfilled request (redacted)'),
  ('gdpr','Art. 16','Let data subjects correct inaccurate or incomplete personal data, and propagate corrections to processors.',
    E'Rectification procedure\nRequest log\nRecord of corrections passed to processors'),
  ('gdpr','Art. 17','Honour valid erasure requests and delete personal data across systems and backups where required.',
    E'Erasure procedure\nDeletion request log\nDeletion confirmation across systems'),
  ('gdpr','Art. 18','Support restriction of processing on valid grounds, flagging affected records so they are not processed further.',
    E'Restriction procedure\nRecord of restricted data\nSystem flags for restriction'),
  ('gdpr','Art. 20','Provide the personal data the subject gave you in a structured, commonly used, machine-readable format.',
    E'Export feature and format (e.g. JSON or CSV)\nPortability procedure\nSample export'),
  ('gdpr','Art. 25','Build privacy into systems by default: minimise data, limit access, and apply pseudonymisation where feasible.',
    E'Data-protection-by-design review in design docs\nDefault privacy settings\nData-minimisation evidence'),
  ('gdpr','Art. 28','Put a Data Processing Agreement in place with every processor, containing the Article 28 required terms.',
    E'Signed DPAs\nProcessor inventory\nDue-diligence records'),
  ('gdpr','Art. 30','Maintain a Record of Processing Activities covering purposes, categories, recipients, transfers, and retention.',
    E'RoPA document\nData inventory\nInternational-transfer records'),
  ('gdpr','Art. 32','Implement appropriate technical and organisational measures: encryption, access control, resilience, and testing.',
    E'Security policy\nEncryption and access-control configuration\nPen-test or risk assessment'),
  ('gdpr','Art. 33-34','Be able to detect, assess, and notify personal-data breaches: the supervisory authority within 72 hours, and data subjects where the risk is high.',
    E'Breach response procedure\nBreach register\nNotification templates'),
  ('gdpr','Art. 35','Perform a Data Protection Impact Assessment for high-risk processing before you start, documenting risks and mitigations.',
    E'DPIA template\nCompleted DPIAs\nDPIA screening criteria'),
  ('gdpr','Art. 37','Where required, appoint a Data Protection Officer with appropriate independence and resources, and publish their contact details.',
    E'DPO appointment record\nPublished DPO contact\nDPO reporting line')
) as v(fw, code, guidance, evidence)
where c.code = v.code
  and c.framework_id = (select id from public.frameworks where slug = v.fw);
